name = "singchineseonline"
main = "worker.js"
compatibility_date = "2026-05-29"

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "LYRIC_TRANSLATION_CACHE"
id = "23f6dfa32be9402b9aa270eebb3d9ee6"
